scheduler:
  contract:
    timeout: 5000

metrics:
  time:
    low: 180
    high: 60

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

